db:
  image: mdillon/postgis
redis:
  image: redis:3.0.3
citygram:
  build: .
  env_file: .env.sample
  environment:
    DB_NAME: citygram_development
    PG_USER: postgres
    PG_HOST: citygram_db_1
    DATABASE_URL: postgres://postgres@citygram_db_1/citygram_development
    REDIS_PROVIDER: REDIS_URL
    REDIS_URL: redis://redis:6379/
  command: bundle exec foreman start -f Procfile.docker
  volumes:
    - .:/usr/src/app/citygram
  ports:
    - "5000:5000"
  links:
    - db
    - redis
